max_width = 96
hard_tabs = false
tab_spaces = 4
use_small_heuristics = "Off"
trailing_comma = "Always"
fn_call_style = "Block"
quote_style = "Double"
space_before_colon = false
normalize_doc_attributes = true
struct_field_align_threshold = 0
match_arm_blocks = false
newline_style = "Unix"
